services:
  # ========================
  # DATABASES
  # ========================

  main-db:
    image: postgres:16
    container_name: main-db
    restart: unless-stopped
    env_file: app/backend/main/src/core/env_files/.env
    volumes:
      - main-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  # ========================
  # ALEMBIC MIGRATIONS
  # ========================

  main_alembic:
    build:
      context: .
      dockerfile: app/backend/main/main_alembic/Dockerfile
    container_name: main_alembic
    env_file: app/backend/main/src/core/env_files/.env
    depends_on:
      main-db:
        condition: service_healthy
    volumes:
      - ./app/backend/main/main_alembic/alembic/versions:/app/backend/main/main_alembic/alembic/versions

  # ========================
  # MAIN SERVICES
  # ========================

  main:
    build:
      context: .
      dockerfile: app/backend/main/src/Dockerfile
    container_name: main-service
    env_file: app/backend/main/src/core/env_files/.env
    depends_on:
      main-db:
        condition: service_healthy
    ports:
      - "9092:8000"

volumes:
  main-db-data:
